<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FacturaController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-FacturaController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\FacturaController' => array('facturasAction' => array(0 => 'security.access.method_interceptor'), 'createFacturaMasivaAction' => array(0 => 'security.access.method_interceptor'), 'cambiarProcesarFacturaMasivaAutoAction' => array(0 => 'security.access.method_interceptor'), 'procesarFacturaMasivaAction' => array(0 => 'security.access.method_interceptor'), 'clonarAccion' => array(0 => 'security.access.method_interceptor'), 'anularAccion' => array(0 => 'security.access.method_interceptor'), 'eliminarAccion' => array(0 => 'security.access.method_interceptor'), 'procesarAccion' => array(0 => 'security.access.method_interceptor'), 'sendEmail' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'descargarAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'cargarFacturaAction' => array(0 => 'security.access.method_interceptor'), 'cargarFacturaErrorAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_18a53ef5491c778a5a5049cdb7db7fd638e8f30d\__CG__\FactelBundle\Controller\FacturaController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
