<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ReporteController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-ReporteController.php';
        $o = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\ReporteController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'reporteVentasAction' => array(0 => 'security.access.method_interceptor'), 'reporteVentasDetalladaAction' => array(0 => 'security.access.method_interceptor'), 'notaCreditoAction' => array(0 => 'security.access.method_interceptor'), 'liquidacionCompraAction' => array(0 => 'security.access.method_interceptor'), 'notaDebitoAction' => array(0 => 'security.access.method_interceptor'), 'retencionAction' => array(0 => 'security.access.method_interceptor'), 'guiaAction' => array(0 => 'security.access.method_interceptor'), 'facturasAction' => array(0 => 'security.access.method_interceptor'), 'reporteRetencionesTotalizadoAction' => array(0 => 'security.access.method_interceptor'), 'retencionTotalizadaAction' => array(0 => 'security.access.method_interceptor'), 'descargarExcel' => array(0 => 'security.access.method_interceptor'), 'retencionTotalizadaExcel' => array(0 => 'security.access.method_interceptor'), 'reporteRetencionesFacturaAction' => array(0 => 'security.access.method_interceptor'), 'retencionFacturaAction' => array(0 => 'security.access.method_interceptor'), 'retencionFacturaExcel' => array(0 => 'security.access.method_interceptor'), 'reporteVentasFechasAction' => array(0 => 'security.access.method_interceptor'), 'descargarPdf' => array(0 => 'security.access.method_interceptor'), 'reporteVentasDetalladaFechasAction' => array(0 => 'security.access.method_interceptor'), 'descargarPdfVentasdetallada' => array(0 => 'security.access.method_interceptor'), 'descargarExcelVentasDetallada' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_c5ff45c299c24cf4a5ac87726cee6c2dcc9dc882\__CG__\FactelBundle\Controller\ReporteController();
        $instance->__CGInterception__setLoader($o);
        return $instance;
    }
}
