<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RoleController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-RoleController.php';
        $q = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\RoleController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_ebdc26b5f94f50af3f5d62d1211befeb4c4c7354\__CG__\FactelBundle\Controller\RoleController();
        $instance->__CGInterception__setLoader($q);
        return $instance;
    }
}
