<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CompraController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-CompraController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\CompraController' => array('comprasAction' => array(0 => 'security.access.method_interceptor'), 'eliminarAccion' => array(0 => 'security.access.method_interceptor'), 'cargarCompraAction' => array(0 => 'security.access.method_interceptor'), 'createCompraFisicaAction' => array(0 => 'security.access.method_interceptor'), 'createCompraAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_a3dce73de7339792d2c1583cfac0f04c5c151254\__CG__\FactelBundle\Controller\CompraController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
