<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PlanController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-PlanController.php';
        $l = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\PlanController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_92e1cbd1f7f9a8078632de90b86f15f90097ca82\__CG__\FactelBundle\Controller\PlanController();
        $instance->__CGInterception__setLoader($l);
        return $instance;
    }
}
