<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LiquidacionCompraController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-LiquidacionCompraController.php';
        $i = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\LiquidacionCompraController' => array('liquidacionesAction' => array(0 => 'security.access.method_interceptor'), 'procesarAccion' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'anularAccion' => array(0 => 'security.access.method_interceptor'), 'eliminarAccion' => array(0 => 'security.access.method_interceptor'), 'descargarAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_02b16ef5951b08e87be0dbf4b467fd75d3516d85\__CG__\FactelBundle\Controller\LiquidacionCompraController();
        $instance->__CGInterception__setLoader($i);
        return $instance;
    }
}
