<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InicioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FactelBundle\Controller\InicioController();
        return $instance;
    }
}
