<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImpuestoIRBPNRController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-ImpuestoIRBPNRController.php';
        $g = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\ImpuestoIRBPNRController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_41195960270c9a1984b88cddc80d023e47641088\__CG__\FactelBundle\Controller\ImpuestoIRBPNRController();
        $instance->__CGInterception__setLoader($g);
        return $instance;
    }
}
