<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EstablecimientoController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-EstablecimientoController.php';
        $c = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\EstablecimientoController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_1bc03a562aaf644cf5cedafc425843e0509df8f9\__CG__\FactelBundle\Controller\EstablecimientoController();
        $instance->__CGInterception__setLoader($c);
        return $instance;
    }
}
