<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImpuestoICEController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/renesan1/public_html/1/app/cache/prod/jms_diextra/proxies/FactelBundle-Controller-ImpuestoICEController.php';
        $f = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\ImpuestoICEController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy250234c8_4380344862658a4d33709651554725edc57d1aa6\__CG__\FactelBundle\Controller\ImpuestoICEController();
        $instance->__CGInterception__setLoader($f);
        return $instance;
    }
}
