<?php

namespace Proxies\__CG__\FactelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proforma extends \FactelBundle\Entity\Proforma implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'numero', 'estado', 'fechaEmision', 'nombreArchivo', 'cliente', 'emisor', 'establecimiento', 'composAdic', 'proformasHasProducto', 'mensajes', 'totalSinImpuestos', 'subtotal12', 'subtotal0', 'iva12', 'totalDescuento', 'valorTotal', 'observacion', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
        }

        return ['__isInitialized__', 'id', 'numero', 'estado', 'fechaEmision', 'nombreArchivo', 'cliente', 'emisor', 'establecimiento', 'composAdic', 'proformasHasProducto', 'mensajes', 'totalSinImpuestos', 'subtotal12', 'subtotal0', 'iva12', 'totalDescuento', 'valorTotal', 'observacion', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proforma $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEmision($fechaEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEmision', [$fechaEmision]);

        return parent::setFechaEmision($fechaEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEmision', []);

        return parent::getFechaEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreArchivo($nombreArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreArchivo', [$nombreArchivo]);

        return parent::setNombreArchivo($nombreArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreArchivo', []);

        return parent::getNombreArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalSinImpuestos($totalSinImpuestos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalSinImpuestos', [$totalSinImpuestos]);

        return parent::setTotalSinImpuestos($totalSinImpuestos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSinImpuestos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSinImpuestos', []);

        return parent::getTotalSinImpuestos();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal12($subtotal12)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal12', [$subtotal12]);

        return parent::setSubtotal12($subtotal12);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal12()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal12', []);

        return parent::getSubtotal12();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal0($subtotal0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal0', [$subtotal0]);

        return parent::setSubtotal0($subtotal0);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal0()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal0', []);

        return parent::getSubtotal0();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva12($iva12)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva12', [$iva12]);

        return parent::setIva12($iva12);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva12()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva12', []);

        return parent::getIva12();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalDescuento($totalDescuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalDescuento', [$totalDescuento]);

        return parent::setTotalDescuento($totalDescuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalDescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalDescuento', []);

        return parent::getTotalDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTotal($valorTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTotal', [$valorTotal]);

        return parent::setValorTotal($valorTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTotal', []);

        return parent::getValorTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\FactelBundle\Entity\Cliente $cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmisor(\FactelBundle\Entity\Emisor $emisor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmisor', [$emisor]);

        return parent::setEmisor($emisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmisor', []);

        return parent::getEmisor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstablecimiento(\FactelBundle\Entity\Establecimiento $establecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstablecimiento', [$establecimiento]);

        return parent::setEstablecimiento($establecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstablecimiento', []);

        return parent::getEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function addComposAdic(\FactelBundle\Entity\CampoAdicional $composAdic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComposAdic', [$composAdic]);

        return parent::addComposAdic($composAdic);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComposAdic(\FactelBundle\Entity\CampoAdicional $composAdic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComposAdic', [$composAdic]);

        return parent::removeComposAdic($composAdic);
    }

    /**
     * {@inheritDoc}
     */
    public function getComposAdic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComposAdic', []);

        return parent::getComposAdic();
    }

    /**
     * {@inheritDoc}
     */
    public function addProformasHasProducto(\FactelBundle\Entity\ProformaHasProducto $proformasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProformasHasProducto', [$proformasHasProducto]);

        return parent::addProformasHasProducto($proformasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProformasHasProducto(\FactelBundle\Entity\ProformaHasProducto $proformasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProformasHasProducto', [$proformasHasProducto]);

        return parent::removeProformasHasProducto($proformasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProformasHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProformasHasProducto', []);

        return parent::getProformasHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addMensaje(\FactelBundle\Entity\Mensaje $mensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMensaje', [$mensaje]);

        return parent::addMensaje($mensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMensaje(\FactelBundle\Entity\Mensaje $mensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMensaje', [$mensaje]);

        return parent::removeMensaje($mensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensajes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensajes', []);

        return parent::getMensajes();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function updateTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateTimestamps', []);

        return parent::updateTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$user]);

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$user]);

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$user]);

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', []);

        return parent::isBlameable();
    }

}
