<?php

namespace Proxies\__CG__\FactelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Establecimiento extends \FactelBundle\Entity\Establecimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'emisor', 'ptosEmision', 'facturas', 'proformas', 'compras', 'liquidacionescompra', 'notasCredito', 'notasDebito', 'retencion', 'guias', 'nombre', 'codigo', 'urlweb', 'nombreComercial', 'direccion', 'emailCopia', 'activo', 'logo', 'dirLogo', 'secuencialProforma', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
        }

        return ['__isInitialized__', 'id', 'emisor', 'ptosEmision', 'facturas', 'proformas', 'compras', 'liquidacionescompra', 'notasCredito', 'notasDebito', 'retencion', 'guias', 'nombre', 'codigo', 'urlweb', 'nombreComercial', 'direccion', 'emailCopia', 'activo', 'logo', 'dirLogo', 'secuencialProforma', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Establecimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmisor(\FactelBundle\Entity\Emisor $emisor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmisor', [$emisor]);

        return parent::setEmisor($emisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmisor', []);

        return parent::getEmisor();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addPtosEmision(\FactelBundle\Entity\PtoEmision $ptosEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPtosEmision', [$ptosEmision]);

        return parent::addPtosEmision($ptosEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function removePtosEmision(\FactelBundle\Entity\PtoEmision $ptosEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePtosEmision', [$ptosEmision]);

        return parent::removePtosEmision($ptosEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getPtosEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPtosEmision', []);

        return parent::getPtosEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function addFactura(\FactelBundle\Entity\Factura $facturas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFactura', [$facturas]);

        return parent::addFactura($facturas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFactura(\FactelBundle\Entity\Factura $facturas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFactura', [$facturas]);

        return parent::removeFactura($facturas);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturas', []);

        return parent::getFacturas();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotasCredito(\FactelBundle\Entity\NotaCredito $notasCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotasCredito', [$notasCredito]);

        return parent::addNotasCredito($notasCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotasCredito(\FactelBundle\Entity\NotaCredito $notasCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotasCredito', [$notasCredito]);

        return parent::removeNotasCredito($notasCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotasCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotasCredito', []);

        return parent::getNotasCredito();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotasDebito(\FactelBundle\Entity\NotaDebito $notasDebito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotasDebito', [$notasDebito]);

        return parent::addNotasDebito($notasDebito);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotasDebito(\FactelBundle\Entity\NotaDebito $notasDebito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotasDebito', [$notasDebito]);

        return parent::removeNotasDebito($notasDebito);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotasDebito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotasDebito', []);

        return parent::getNotasDebito();
    }

    /**
     * {@inheritDoc}
     */
    public function addRetencion(\FactelBundle\Entity\Retencion $retencion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRetencion', [$retencion]);

        return parent::addRetencion($retencion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRetencion(\FactelBundle\Entity\Retencion $retencion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRetencion', [$retencion]);

        return parent::removeRetencion($retencion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetencion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetencion', []);

        return parent::getRetencion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlweb($urlweb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlweb', [$urlweb]);

        return parent::setUrlweb($urlweb);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlweb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlweb', []);

        return parent::getUrlweb();
    }

    /**
     * {@inheritDoc}
     */
    public function addGuia(\FactelBundle\Entity\Guia $guia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGuia', [$guia]);

        return parent::addGuia($guia);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGuia(\FactelBundle\Entity\Guia $guia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGuia', [$guia]);

        return parent::removeGuia($guia);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuias', []);

        return parent::getGuias();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreComercial($nombreComercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreComercial', [$nombreComercial]);

        return parent::setNombreComercial($nombreComercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreComercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreComercial', []);

        return parent::getNombreComercial();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDirLogo($dirLogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirLogo', [$dirLogo]);

        return parent::setDirLogo($dirLogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirLogo', []);

        return parent::getDirLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCopia($emailCopia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCopia', [$emailCopia]);

        return parent::setEmailCopia($emailCopia);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCopia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCopia', []);

        return parent::getEmailCopia();
    }

    /**
     * {@inheritDoc}
     */
    public function addLiquidacionescompra(\FactelBundle\Entity\LiquidacionCompra $liquidacionescompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLiquidacionescompra', [$liquidacionescompra]);

        return parent::addLiquidacionescompra($liquidacionescompra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLiquidacionescompra(\FactelBundle\Entity\LiquidacionCompra $liquidacionescompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLiquidacionescompra', [$liquidacionescompra]);

        return parent::removeLiquidacionescompra($liquidacionescompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getLiquidacionescompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiquidacionescompra', []);

        return parent::getLiquidacionescompra();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompra(\FactelBundle\Entity\Compra $compra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompra', [$compra]);

        return parent::addCompra($compra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompra(\FactelBundle\Entity\Compra $compra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompra', [$compra]);

        return parent::removeCompra($compra);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompras', []);

        return parent::getCompras();
    }

    /**
     * {@inheritDoc}
     */
    public function addProforma(\FactelBundle\Entity\Proforma $proforma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProforma', [$proforma]);

        return parent::addProforma($proforma);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProforma(\FactelBundle\Entity\Proforma $proforma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProforma', [$proforma]);

        return parent::removeProforma($proforma);
    }

    /**
     * {@inheritDoc}
     */
    public function getProformas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProformas', []);

        return parent::getProformas();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecuencialProforma($secuencialProforma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecuencialProforma', [$secuencialProforma]);

        return parent::setSecuencialProforma($secuencialProforma);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecuencialProforma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecuencialProforma', []);

        return parent::getSecuencialProforma();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function updateTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateTimestamps', []);

        return parent::updateTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$user]);

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$user]);

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$user]);

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', []);

        return parent::isBlameable();
    }

}
