<?php

namespace Proxies\__CG__\FactelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \FactelBundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'emisor', 'impuestoIVA', 'impuestoICE', 'impuestoIRBPNR', 'facturasHasProducto', 'proformasHasProducto', 'liquidacionesCompraHasProducto', 'guiasHasProducto', 'notaCreditoHasProducto', 'codigoPrincipal', 'codigoAuxiliar', 'nombre', 'precioUnitario', '' . "\0" . 'FactelBundle\\Entity\\Producto' . "\0" . 'tieneSubsidio', 'precioSinSubsidio', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
        }

        return ['__isInitialized__', 'id', 'emisor', 'impuestoIVA', 'impuestoICE', 'impuestoIRBPNR', 'facturasHasProducto', 'proformasHasProducto', 'liquidacionesCompraHasProducto', 'guiasHasProducto', 'notaCreditoHasProducto', 'codigoPrincipal', 'codigoAuxiliar', 'nombre', 'precioUnitario', '' . "\0" . 'FactelBundle\\Entity\\Producto' . "\0" . 'tieneSubsidio', 'precioSinSubsidio', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPrincipal($codigoPrincipal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPrincipal', [$codigoPrincipal]);

        return parent::setCodigoPrincipal($codigoPrincipal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPrincipal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPrincipal', []);

        return parent::getCodigoPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoAuxiliar($codigoAuxiliar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoAuxiliar', [$codigoAuxiliar]);

        return parent::setCodigoAuxiliar($codigoAuxiliar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoAuxiliar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoAuxiliar', []);

        return parent::getCodigoAuxiliar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioUnitario($precioUnitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioUnitario', [$precioUnitario]);

        return parent::setPrecioUnitario($precioUnitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioUnitario', []);

        return parent::getPrecioUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmisor(\FactelBundle\Entity\Emisor $emisor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmisor', [$emisor]);

        return parent::setEmisor($emisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmisor', []);

        return parent::getEmisor();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoIVA(\FactelBundle\Entity\ImpuestoIVA $impuestoIVA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoIVA', [$impuestoIVA]);

        return parent::setImpuestoIVA($impuestoIVA);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoIVA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoIVA', []);

        return parent::getImpuestoIVA();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoICE(\FactelBundle\Entity\ImpuestoICE $impuestoICE = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoICE', [$impuestoICE]);

        return parent::setImpuestoICE($impuestoICE);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoICE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoICE', []);

        return parent::getImpuestoICE();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoIRBPNR(\FactelBundle\Entity\ImpuestoIRBPNR $impuestoIRBPNR = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoIRBPNR', [$impuestoIRBPNR]);

        return parent::setImpuestoIRBPNR($impuestoIRBPNR);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoIRBPNR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoIRBPNR', []);

        return parent::getImpuestoIRBPNR();
    }

    /**
     * {@inheritDoc}
     */
    public function addFacturasHasProducto(\FactelBundle\Entity\FacturaHasProducto $facturasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFacturasHasProducto', [$facturasHasProducto]);

        return parent::addFacturasHasProducto($facturasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFacturasHasProducto(\FactelBundle\Entity\FacturaHasProducto $facturasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFacturasHasProducto', [$facturasHasProducto]);

        return parent::removeFacturasHasProducto($facturasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturasHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturasHasProducto', []);

        return parent::getFacturasHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotaCreditoHasProducto(\FactelBundle\Entity\NotaCreditoHasProducto $notaCreditoHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotaCreditoHasProducto', [$notaCreditoHasProducto]);

        return parent::addNotaCreditoHasProducto($notaCreditoHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotaCreditoHasProducto(\FactelBundle\Entity\NotaCreditoHasProducto $notaCreditoHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotaCreditoHasProducto', [$notaCreditoHasProducto]);

        return parent::removeNotaCreditoHasProducto($notaCreditoHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotaCreditoHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotaCreditoHasProducto', []);

        return parent::getNotaCreditoHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addGuiasHasProducto(\FactelBundle\Entity\GuiaHasProducto $guiasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGuiasHasProducto', [$guiasHasProducto]);

        return parent::addGuiasHasProducto($guiasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGuiasHasProducto(\FactelBundle\Entity\GuiaHasProducto $guiasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGuiasHasProducto', [$guiasHasProducto]);

        return parent::removeGuiasHasProducto($guiasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiasHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiasHasProducto', []);

        return parent::getGuiasHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addLiquidacionesCompraHasProducto(\FactelBundle\Entity\LiquidacionCompraHasProducto $liquidacionesCompraHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLiquidacionesCompraHasProducto', [$liquidacionesCompraHasProducto]);

        return parent::addLiquidacionesCompraHasProducto($liquidacionesCompraHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLiquidacionesCompraHasProducto(\FactelBundle\Entity\LiquidacionCompraHasProducto $liquidacionesCompraHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLiquidacionesCompraHasProducto', [$liquidacionesCompraHasProducto]);

        return parent::removeLiquidacionesCompraHasProducto($liquidacionesCompraHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getLiquidacionesCompraHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiquidacionesCompraHasProducto', []);

        return parent::getLiquidacionesCompraHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTieneSubsidio($tieneSubsidio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTieneSubsidio', [$tieneSubsidio]);

        return parent::setTieneSubsidio($tieneSubsidio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTieneSubsidio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTieneSubsidio', []);

        return parent::getTieneSubsidio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioSinSubsidio($precioSinSubsidio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioSinSubsidio', [$precioSinSubsidio]);

        return parent::setPrecioSinSubsidio($precioSinSubsidio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioSinSubsidio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioSinSubsidio', []);

        return parent::getPrecioSinSubsidio();
    }

    /**
     * {@inheritDoc}
     */
    public function addProformasHasProducto(\FactelBundle\Entity\ProformaHasProducto $proformasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProformasHasProducto', [$proformasHasProducto]);

        return parent::addProformasHasProducto($proformasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProformasHasProducto(\FactelBundle\Entity\ProformaHasProducto $proformasHasProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProformasHasProducto', [$proformasHasProducto]);

        return parent::removeProformasHasProducto($proformasHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProformasHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProformasHasProducto', []);

        return parent::getProformasHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function updateTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateTimestamps', []);

        return parent::updateTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$user]);

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$user]);

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$user]);

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', []);

        return parent::isBlameable();
    }

}
