<?php

namespace Proxies\__CG__\FactelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Impuesto extends \FactelBundle\Entity\Impuesto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'facturaHasProducto', 'proformaHasProducto', 'liquidacionCompraHasProducto', 'notaCreditoHasProducto', 'notaDebito', 'codigo', 'codigoPorcentaje', 'tarifa', 'baseImponible', 'valor'];
        }

        return ['__isInitialized__', 'id', 'facturaHasProducto', 'proformaHasProducto', 'liquidacionCompraHasProducto', 'notaCreditoHasProducto', 'notaDebito', 'codigo', 'codigoPorcentaje', 'tarifa', 'baseImponible', 'valor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Impuesto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPorcentaje($codigoPorcentaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPorcentaje', [$codigoPorcentaje]);

        return parent::setCodigoPorcentaje($codigoPorcentaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPorcentaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPorcentaje', []);

        return parent::getCodigoPorcentaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifa($tarifa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifa', [$tarifa]);

        return parent::setTarifa($tarifa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifa', []);

        return parent::getTarifa();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseImponible($baseImponible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseImponible', [$baseImponible]);

        return parent::setBaseImponible($baseImponible);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseImponible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseImponible', []);

        return parent::getBaseImponible();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', [$valor]);

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', []);

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturaHasProducto(\FactelBundle\Entity\FacturaHasProducto $facturaHasProducto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturaHasProducto', [$facturaHasProducto]);

        return parent::setFacturaHasProducto($facturaHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturaHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturaHasProducto', []);

        return parent::getFacturaHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotaCreditoHasProducto(\FactelBundle\Entity\NotaCreditoHasProducto $notaCreditoHasProducto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotaCreditoHasProducto', [$notaCreditoHasProducto]);

        return parent::setNotaCreditoHasProducto($notaCreditoHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotaCreditoHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotaCreditoHasProducto', []);

        return parent::getNotaCreditoHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotaDebito(\FactelBundle\Entity\NotaDebito $notaDebito = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotaDebito', [$notaDebito]);

        return parent::setNotaDebito($notaDebito);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotaDebito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotaDebito', []);

        return parent::getNotaDebito();
    }

    /**
     * {@inheritDoc}
     */
    public function setLiquidacionCompraHasProducto(\FactelBundle\Entity\LiquidacionCompraHasProducto $liquidacionCompraHasProducto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLiquidacionCompraHasProducto', [$liquidacionCompraHasProducto]);

        return parent::setLiquidacionCompraHasProducto($liquidacionCompraHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getLiquidacionCompraHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiquidacionCompraHasProducto', []);

        return parent::getLiquidacionCompraHasProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProformaHasProducto(\FactelBundle\Entity\ProformaHasProducto $proformaHasProducto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProformaHasProducto', [$proformaHasProducto]);

        return parent::setProformaHasProducto($proformaHasProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProformaHasProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProformaHasProducto', []);

        return parent::getProformaHasProducto();
    }

}
