<?php

namespace Proxies\__CG__\FactelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FacturaReembolso extends \FactelBundle\Entity\FacturaReembolso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'tipoProveedorReembolso', 'tipoIdentificacionProveedorReembolso', 'identificacionProveedorReembolso', 'estabDocReembolso', 'ptoEmiDocReembolso', 'secuencialDocReembolso', 'fechaEmisionDocReembolso', 'numeroautorizacionDocReemb', 'codDocReembolso', 'baseImponibleReembolso', 'impuestoReembolso', 'baseImponibleSinIvaReembolso', 'factura', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
        }

        return ['__isInitialized__', 'id', 'tipoProveedorReembolso', 'tipoIdentificacionProveedorReembolso', 'identificacionProveedorReembolso', 'estabDocReembolso', 'ptoEmiDocReembolso', 'secuencialDocReembolso', 'fechaEmisionDocReembolso', 'numeroautorizacionDocReemb', 'codDocReembolso', 'baseImponibleReembolso', 'impuestoReembolso', 'baseImponibleSinIvaReembolso', 'factura', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FacturaReembolso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoProveedorReembolso($tipoProveedorReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoProveedorReembolso', [$tipoProveedorReembolso]);

        return parent::setTipoProveedorReembolso($tipoProveedorReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoProveedorReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoProveedorReembolso', []);

        return parent::getTipoProveedorReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodDocReembolso($codDocReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodDocReembolso', [$codDocReembolso]);

        return parent::setCodDocReembolso($codDocReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodDocReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodDocReembolso', []);

        return parent::getCodDocReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseImponibleReembolso($baseImponibleReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseImponibleReembolso', [$baseImponibleReembolso]);

        return parent::setBaseImponibleReembolso($baseImponibleReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseImponibleReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseImponibleReembolso', []);

        return parent::getBaseImponibleReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoReembolso($impuestoReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoReembolso', [$impuestoReembolso]);

        return parent::setImpuestoReembolso($impuestoReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoReembolso', []);

        return parent::getImpuestoReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactura(\FactelBundle\Entity\Factura $factura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactura', [$factura]);

        return parent::setFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactura', []);

        return parent::getFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoIdentificacionProveedorReembolso($tipoIdentificacionProveedorReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoIdentificacionProveedorReembolso', [$tipoIdentificacionProveedorReembolso]);

        return parent::setTipoIdentificacionProveedorReembolso($tipoIdentificacionProveedorReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoIdentificacionProveedorReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoIdentificacionProveedorReembolso', []);

        return parent::getTipoIdentificacionProveedorReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentificacionProveedorReembolso($identificacionProveedorReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificacionProveedorReembolso', [$identificacionProveedorReembolso]);

        return parent::setIdentificacionProveedorReembolso($identificacionProveedorReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificacionProveedorReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificacionProveedorReembolso', []);

        return parent::getIdentificacionProveedorReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstabDocReembolso($estabDocReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstabDocReembolso', [$estabDocReembolso]);

        return parent::setEstabDocReembolso($estabDocReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstabDocReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstabDocReembolso', []);

        return parent::getEstabDocReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPtoEmiDocReembolso($ptoEmiDocReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPtoEmiDocReembolso', [$ptoEmiDocReembolso]);

        return parent::setPtoEmiDocReembolso($ptoEmiDocReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPtoEmiDocReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPtoEmiDocReembolso', []);

        return parent::getPtoEmiDocReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecuencialDocReembolso($secuencialDocReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecuencialDocReembolso', [$secuencialDocReembolso]);

        return parent::setSecuencialDocReembolso($secuencialDocReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecuencialDocReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecuencialDocReembolso', []);

        return parent::getSecuencialDocReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEmisionDocReembolso($fechaEmisionDocReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEmisionDocReembolso', [$fechaEmisionDocReembolso]);

        return parent::setFechaEmisionDocReembolso($fechaEmisionDocReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEmisionDocReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEmisionDocReembolso', []);

        return parent::getFechaEmisionDocReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroautorizacionDocReemb($numeroautorizacionDocReemb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroautorizacionDocReemb', [$numeroautorizacionDocReemb]);

        return parent::setNumeroautorizacionDocReemb($numeroautorizacionDocReemb);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroautorizacionDocReemb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroautorizacionDocReemb', []);

        return parent::getNumeroautorizacionDocReemb();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseImponibleSinIvaReembolso($baseImponibleSinIvaReembolso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseImponibleSinIvaReembolso', [$baseImponibleSinIvaReembolso]);

        return parent::setBaseImponibleSinIvaReembolso($baseImponibleSinIvaReembolso);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseImponibleSinIvaReembolso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseImponibleSinIvaReembolso', []);

        return parent::getBaseImponibleSinIvaReembolso();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function updateTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateTimestamps', []);

        return parent::updateTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$user]);

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$user]);

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$user]);

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', []);

        return parent::isBlameable();
    }

}
