<?php

namespace Proxies\__CG__\FactelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Compra extends \FactelBundle\Entity\Compra implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'claveAcceso', 'numeroAutorizacion', 'fechaAutorizacion', 'numeroFactura', 'fechaEmision', 'razonSocialProveedor', 'nombreComercialProveedor', '' . "\0" . 'FactelBundle\\Entity\\Compra' . "\0" . 'identificacionProveedor', '' . "\0" . 'FactelBundle\\Entity\\Compra' . "\0" . 'direccionMatrizProveedor', '' . "\0" . 'FactelBundle\\Entity\\Compra' . "\0" . 'direccionEstabProveedor', 'emisor', 'establecimiento', 'detallesCompra', 'totalSinImpuestos', 'totalDescuento', 'valorICE', 'subTotalIva0', 'subTotalIva12', 'iva12', 'propina', 'valorTotal', 'retencionCreadaId', 'facturaFisica', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
        }

        return ['__isInitialized__', 'id', 'claveAcceso', 'numeroAutorizacion', 'fechaAutorizacion', 'numeroFactura', 'fechaEmision', 'razonSocialProveedor', 'nombreComercialProveedor', '' . "\0" . 'FactelBundle\\Entity\\Compra' . "\0" . 'identificacionProveedor', '' . "\0" . 'FactelBundle\\Entity\\Compra' . "\0" . 'direccionMatrizProveedor', '' . "\0" . 'FactelBundle\\Entity\\Compra' . "\0" . 'direccionEstabProveedor', 'emisor', 'establecimiento', 'detallesCompra', 'totalSinImpuestos', 'totalDescuento', 'valorICE', 'subTotalIva0', 'subTotalIva12', 'iva12', 'propina', 'valorTotal', 'retencionCreadaId', 'facturaFisica', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Compra $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaveAcceso($claveAcceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaveAcceso', [$claveAcceso]);

        return parent::setClaveAcceso($claveAcceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaveAcceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaveAcceso', []);

        return parent::getClaveAcceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroAutorizacion($numeroAutorizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroAutorizacion', [$numeroAutorizacion]);

        return parent::setNumeroAutorizacion($numeroAutorizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroAutorizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroAutorizacion', []);

        return parent::getNumeroAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAutorizacion($fechaAutorizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAutorizacion', [$fechaAutorizacion]);

        return parent::setFechaAutorizacion($fechaAutorizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAutorizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAutorizacion', []);

        return parent::getFechaAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFactura($numeroFactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFactura', [$numeroFactura]);

        return parent::setNumeroFactura($numeroFactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFactura', []);

        return parent::getNumeroFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEmision($fechaEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEmision', [$fechaEmision]);

        return parent::setFechaEmision($fechaEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEmision', []);

        return parent::getFechaEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonSocialProveedor($razonSocialProveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonSocialProveedor', [$razonSocialProveedor]);

        return parent::setRazonSocialProveedor($razonSocialProveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonSocialProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonSocialProveedor', []);

        return parent::getRazonSocialProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreComercialProveedor($nombreComercialProveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreComercialProveedor', [$nombreComercialProveedor]);

        return parent::setNombreComercialProveedor($nombreComercialProveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreComercialProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreComercialProveedor', []);

        return parent::getNombreComercialProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentificacionProveedor($identificacionProveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificacionProveedor', [$identificacionProveedor]);

        return parent::setIdentificacionProveedor($identificacionProveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificacionProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificacionProveedor', []);

        return parent::getIdentificacionProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionMatrizProveedor($direccionMatrizProveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionMatrizProveedor', [$direccionMatrizProveedor]);

        return parent::setDireccionMatrizProveedor($direccionMatrizProveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionMatrizProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionMatrizProveedor', []);

        return parent::getDireccionMatrizProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionEstabProveedor($direccionEstabProveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionEstabProveedor', [$direccionEstabProveedor]);

        return parent::setDireccionEstabProveedor($direccionEstabProveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionEstabProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionEstabProveedor', []);

        return parent::getDireccionEstabProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalSinImpuestos($totalSinImpuestos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalSinImpuestos', [$totalSinImpuestos]);

        return parent::setTotalSinImpuestos($totalSinImpuestos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSinImpuestos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSinImpuestos', []);

        return parent::getTotalSinImpuestos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalDescuento($totalDescuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalDescuento', [$totalDescuento]);

        return parent::setTotalDescuento($totalDescuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalDescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalDescuento', []);

        return parent::getTotalDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorICE($valorICE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorICE', [$valorICE]);

        return parent::setValorICE($valorICE);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorICE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorICE', []);

        return parent::getValorICE();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubTotalIva0($subTotalIva0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubTotalIva0', [$subTotalIva0]);

        return parent::setSubTotalIva0($subTotalIva0);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTotalIva0()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTotalIva0', []);

        return parent::getSubTotalIva0();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubTotalIva12($subTotalIva12)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubTotalIva12', [$subTotalIva12]);

        return parent::setSubTotalIva12($subTotalIva12);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTotalIva12()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTotalIva12', []);

        return parent::getSubTotalIva12();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva12($iva12)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva12', [$iva12]);

        return parent::setIva12($iva12);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva12()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva12', []);

        return parent::getIva12();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropina($propina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropina', [$propina]);

        return parent::setPropina($propina);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropina', []);

        return parent::getPropina();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTotal($valorTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTotal', [$valorTotal]);

        return parent::setValorTotal($valorTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTotal', []);

        return parent::getValorTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmisor(\FactelBundle\Entity\Emisor $emisor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmisor', [$emisor]);

        return parent::setEmisor($emisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmisor', []);

        return parent::getEmisor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstablecimiento(\FactelBundle\Entity\Establecimiento $establecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstablecimiento', [$establecimiento]);

        return parent::setEstablecimiento($establecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstablecimiento', []);

        return parent::getEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetallesCompra(\FactelBundle\Entity\DetalleCompra $detallesCompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetallesCompra', [$detallesCompra]);

        return parent::addDetallesCompra($detallesCompra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetallesCompra(\FactelBundle\Entity\DetalleCompra $detallesCompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetallesCompra', [$detallesCompra]);

        return parent::removeDetallesCompra($detallesCompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetallesCompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetallesCompra', []);

        return parent::getDetallesCompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setRetencionCreadaId($retencionCreadaId = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRetencionCreadaId', [$retencionCreadaId]);

        return parent::setRetencionCreadaId($retencionCreadaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetencionCreadaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetencionCreadaId', []);

        return parent::getRetencionCreadaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturaFisica($facturaFisica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturaFisica', [$facturaFisica]);

        return parent::setFacturaFisica($facturaFisica);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturaFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturaFisica', []);

        return parent::getFacturaFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function updateTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateTimestamps', []);

        return parent::updateTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$user]);

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$user]);

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$user]);

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', []);

        return parent::isBlameable();
    }

}
